#!/bin/bash
# =============================================================================
# TWOINE - SFTP Configuration Setup Script
# Configures OpenSSH for chrooted SFTP access
# =============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
SITES_DIR="${SITES_DIR:-/var/www/sites}"
SFTP_GROUP="sftpusers"
SSHD_CONFIG="/etc/ssh/sshd_config"
SSHD_CONFIG_DIR="/etc/ssh/sshd_config.d"
TWOINE_SFTP_CONFIG="${SSHD_CONFIG_DIR}/twoine-sftp.conf"

# Functions
log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    log_error "This script must be run as root"
    exit 1
fi

echo ""
echo "=============================================="
echo "  TWOINE - SFTP Configuration Setup"
echo "=============================================="
echo ""

# =============================================================================
# STEP 1: Check OpenSSH installation
# =============================================================================
log_step "1. Checking OpenSSH installation..."

if ! command -v sshd &> /dev/null; then
    log_info "Installing OpenSSH server..."
    apt-get update
    apt-get install -y openssh-server
fi

log_info "OpenSSH is installed: $(sshd -V 2>&1 | head -1)"

# =============================================================================
# STEP 2: Create SFTP group
# =============================================================================
log_step "2. Creating SFTP group..."

if ! getent group "$SFTP_GROUP" > /dev/null 2>&1; then
    groupadd "$SFTP_GROUP"
    log_info "Created group: ${SFTP_GROUP}"
else
    log_info "Group '${SFTP_GROUP}' already exists"
fi

# =============================================================================
# STEP 3: Create sites directory
# =============================================================================
log_step "3. Creating sites directory..."

mkdir -p "$SITES_DIR"
chown root:root "$SITES_DIR"
chmod 755 "$SITES_DIR"
log_info "Sites directory: ${SITES_DIR}"

# =============================================================================
# STEP 4: Backup original sshd_config
# =============================================================================
log_step "4. Backing up SSH configuration..."

BACKUP_FILE="${SSHD_CONFIG}.twoine-backup.$(date +%Y%m%d%H%M%S)"
cp "$SSHD_CONFIG" "$BACKUP_FILE"
log_info "Backup created: ${BACKUP_FILE}"

# =============================================================================
# STEP 5: Create Twoine SFTP configuration
# =============================================================================
log_step "5. Creating Twoine SFTP configuration..."

mkdir -p "$SSHD_CONFIG_DIR"

cat > "$TWOINE_SFTP_CONFIG" << 'SFTPCONF'
# =============================================================================
# TWOINE SFTP Configuration
# Generated by setup-sftp.sh
# =============================================================================

# Match all users in the sftpusers group
Match Group sftpusers
    # Force SFTP subsystem only (no shell access)
    ForceCommand internal-sftp -u 0002 -l INFO
    
    # Chroot to /var/www/sites
    # User will only see their site directory
    ChrootDirectory /var/www/sites/%u
    
    # Disable all forwarding and tunneling
    AllowTcpForwarding no
    X11Forwarding no
    PermitTunnel no
    AllowAgentForwarding no
    
    # Disable TTY allocation
    PermitTTY no
    
    # Authentication settings
    PasswordAuthentication yes
    PubkeyAuthentication yes
    
    # Logging
    LogLevel VERBOSE

SFTPCONF

log_info "Created: ${TWOINE_SFTP_CONFIG}"

# =============================================================================
# STEP 6: Ensure sshd_config includes config.d directory
# =============================================================================
log_step "6. Ensuring sshd_config includes config.d..."

if ! grep -q "^Include ${SSHD_CONFIG_DIR}" "$SSHD_CONFIG"; then
    # Add Include directive at the beginning (after comments)
    sed -i "1a Include ${SSHD_CONFIG_DIR}/*.conf" "$SSHD_CONFIG"
    log_info "Added Include directive to sshd_config"
else
    log_info "Include directive already present"
fi

# =============================================================================
# STEP 7: Validate SSH configuration
# =============================================================================
log_step "7. Validating SSH configuration..."

if sshd -t; then
    log_info "SSH configuration is valid"
else
    log_error "SSH configuration is invalid!"
    log_error "Restoring backup..."
    cp "$BACKUP_FILE" "$SSHD_CONFIG"
    rm -f "$TWOINE_SFTP_CONFIG"
    exit 1
fi

# =============================================================================
# STEP 8: Restart SSH service
# =============================================================================
log_step "8. Restarting SSH service..."

systemctl restart sshd
log_info "SSH service restarted"

# =============================================================================
# STEP 9: Verify SSH is running
# =============================================================================
log_step "9. Verifying SSH service..."

if systemctl is-active --quiet sshd; then
    log_info "SSH service is running"
else
    log_error "SSH service failed to start!"
    exit 1
fi

# =============================================================================
# OUTPUT
# =============================================================================
echo ""
echo "=============================================="
echo -e "${GREEN}SFTP Configuration Complete${NC}"
echo "=============================================="
echo ""
echo "Configuration:"
echo "  SFTP Group:     ${SFTP_GROUP}"
echo "  Sites Dir:      ${SITES_DIR}"
echo "  Config File:    ${TWOINE_SFTP_CONFIG}"
echo "  Backup:         ${BACKUP_FILE}"
echo ""
echo "Chroot Structure (per site):"
echo "  /var/www/sites/site_<name>/"
echo "    ├── services/   (user writable)"
echo "    ├── data/       (user writable)"
echo "    ├── uploads/    (user writable)"
echo "    ├── logs/       (user writable)"
echo "    └── tmp/        (user writable)"
echo ""
echo "To create an SFTP user:"
echo "  ./scripts/sftp-user-create.sh <site_name> [password]"
echo ""
echo "=============================================="
